spring:
  main:
    banner-mode: off
    web-application-type: servlet
  profiles:
    include:
      - h2
      - session
      - access
      - actuator
  mvc:
    async:
      request-timeout: 1m
  task:
    scheduling:
      enabled: true
      env: default
      shutdown:
        await-termination: on
  data:
    redis:
      host: localhost
      port: 6379
      username:
      password: redispass
  cache:
    redis:
      enable-statistics: on
      time-to-live: 1h
      cache-null-values: false
server:
  compression:
    enabled: true
  undertow:
    max-http-post-size: 10MB
    max-headers: 50
    max-cookies: 100
    always-set-keep-alive: on
logging:
  file:
    path: logs
    name: app.log
